#ifndef _CWMP_DATAMODEL_H_
#define _CWMP_DATAMODEL_H_

#define NUM_OBJECTS 100

char *name_func_table[NUM_OBJECTS][3] = {
	{"InternetGatewayDevice.",
			(void *)_InternetGatewayDevice, (char *)49},
	{"DeviceInfo.",
			(void *)_DeviceInfo, (char *)1},
	{"DeviceInfo.VendorConfigFile.i.",
			(void *)_DeviceInfo_VendorConfigFile_i, (char *)0},
	{"DeviceConfig.",
			(void *)_DeviceConfig, (char *)0},
	{"ManagementServer.",
			(void *)_ManagementServer, (char *)0},
	{"Time.",
			(void *)_Time, (char *)0},
	{"UserInterface.",
			(void *)_UserInterface, (char *)0},
	{"Layer3Forwarding.",
			(void *)_Layer3Forwarding, (char *)1},
	{"Layer3Forwarding.Forwarding.i.",
			(void *)_Layer3Forwarding_Forwarding_i, (char *)0},
	{"LANConfigSecurity.",
			(void *)_LANConfigSecurity, (char *)0},
	{"IPPingDiagnostics.",
			(void *)_IPPingDiagnostics, (char *)0},
	{"LANDevice.i.",
			(void *)_LANDevice_i, (char *)12},
	{"LANDevice.i.LANHostConfigManagement.",
			(void *)_LANDevice_i_LANHostConfigManagement, (char *)1},
	{"LANDevice.i.LANHostConfigManagement.IPInterface.i.",
			(void *)_LANDevice_i_LANHostConfigManagement_IPInterface_i, (char *)0},
	{"LANDevice.i.LANEthernetInterfaceConfig.i.",
			(void *)_LANDevice_i_LANEthernetInterfaceConfig_i, (char *)1},
	{"LANDevice.i.LANEthernetInterfaceConfig.i.Stats.",
			(void *)_LANDevice_i_LANEthernetInterfaceConfig_i_Stats, (char *)0},
	{"LANDevice.i.LANUSBInterfaceConfig.i.",
			(void *)_LANDevice_i_LANUSBInterfaceConfig_i, (char *)1},
	{"LANDevice.i.LANUSBInterfaceConfig.i.Stats.",
			(void *)_LANDevice_i_LANUSBInterfaceConfig_i_Stats, (char *)0},
	{"LANDevice.i.WLANConfiguration.i.",
			(void *)_LANDevice_i_WLANConfiguration_i, (char *)3},
	{"LANDevice.i.WLANConfiguration.i.AssociatedDevice.i.",
			(void *)_LANDevice_i_WLANConfiguration_i_AssociatedDevice_i, (char *)0},
	{"LANDevice.i.WLANConfiguration.i.WEPKey.i.",
			(void *)_LANDevice_i_WLANConfiguration_i_WEPKey_i, (char *)0},
	{"LANDevice.i.WLANConfiguration.i.PreSharedKey.i.",
			(void *)_LANDevice_i_WLANConfiguration_i_PreSharedKey_i, (char *)0},
	{"LANDevice.i.Hosts.",
			(void *)_LANDevice_i_Hosts, (char *)1},
	{"LANDevice.i.Hosts.Host.i.",
			(void *)_LANDevice_i_Hosts_Host_i, (char *)0},
	{"WANDevice.i.",
			(void *)_WANDevice_i, (char *)25},
	{"WANDevice.i.WANCommonInterfaceConfig.",
			(void *)_WANDevice_i_WANCommonInterfaceConfig, (char *)1},
	{"WANDevice.i.WANCommonInterfaceConfig.Connection.i.",
			(void *)_WANDevice_i_WANCommonInterfaceConfig_Connection_i, (char *)0},
	{"WANDevice.i.WANDSLInterfaceConfig.",
			(void *)_WANDevice_i_WANDSLInterfaceConfig, (char *)6},
	{"WANDevice.i.WANDSLInterfaceConfig.Stats.",
			(void *)_WANDevice_i_WANDSLInterfaceConfig_Stats, (char *)5},
	{"WANDevice.i.WANDSLInterfaceConfig.Stats.Total.",
			(void *)_WANDevice_i_WANDSLInterfaceConfig_Stats_Total, (char *)0},
	{"WANDevice.i.WANDSLInterfaceConfig.Stats.Showtime.",
			(void *)_WANDevice_i_WANDSLInterfaceConfig_Stats_Showtime, (char *)0},
	{"WANDevice.i.WANDSLInterfaceConfig.Stats.LastShowtime.",
			(void *)_WANDevice_i_WANDSLInterfaceConfig_Stats_LastShowtime, (char *)0},
	{"WANDevice.i.WANDSLInterfaceConfig.Stats.CurrentDay.",
			(void *)_WANDevice_i_WANDSLInterfaceConfig_Stats_CurrentDay, (char *)0},
	{"WANDevice.i.WANDSLInterfaceConfig.Stats.QuarterHour.",
			(void *)_WANDevice_i_WANDSLInterfaceConfig_Stats_QuarterHour, (char *)0},
	{"WANDevice.i.WANEthernetInterfaceConfig.",
			(void *)_WANDevice_i_WANEthernetInterfaceConfig, (char *)1},
	{"WANDevice.i.WANEthernetInterfaceConfig.Stats.",
			(void *)_WANDevice_i_WANEthernetInterfaceConfig_Stats, (char *)0},
	{"WANDevice.i.WANDSLConnectionManagement.",
			(void *)_WANDevice_i_WANDSLConnectionManagement, (char *)1},
	{"WANDevice.i.WANDSLConnectionManagement.ConnectionService.i.",
			(void *)_WANDevice_i_WANDSLConnectionManagement_ConnectionService_i, (char *)0},
	{"WANDevice.i.WANDSLDiagnostics.",
			(void *)_WANDevice_i_WANDSLDiagnostics, (char *)0},
	{"WANDevice.i.WANConnectionDevice.i",
			(void *)_WANDevice_i_WANConnectionDevice_i, (char *)10},
	{"WANDevice.i.WANConnectionDevice.i.WANDSLLinkConfig.",
			(void *)_WANDevice_i_WANConnectionDevice_i_WANDSLLinkConfig, (char *)0},
	{"WANDevice.i.WANConnectionDevice.i.WANATMF5LoopbackDiagnostics.",
			(void *)_WANDevice_i_WANConnectionDevice_i_WANATMF5LoopbackDiagnostics, (char *)0},
	{"WANDevice.i.WANConnectionDevice.i.WANEthernetLinkConfig.",
			(void *)_WANDevice_i_WANConnectionDevice_i_WANEthernetLinkConfig, (char *)0},
	{"WANDevice.i.WANConnectionDevice.i.WANPOTSLinkConfig.",
			(void *)_WANDevice_i_WANConnectionDevice_i_WANPOTSLinkConfig, (char *)0},
	{"WANDevice.i.WANConnectionDevice.i.WANIPConnection.i.",
			(void *)_WANDevice_i_WANConnectionDevice_i_WANIPConnection_i, (char *)2},
	{"WANDevice.i.WANConnectionDevice.i.WANIPConnection.i.PortMapping.i.",
			(void *)_WANDevice_i_WANConnectionDevice_i_WANIPConnection_i_PortMapping_i, (char *)0},
	{"WANDevice.i.WANConnectionDevice.i.WANIPConnection.i.Stats.",
			(void *)_WANDevice_i_WANConnectionDevice_i_WANIPConnection_i_Stats, (char *)0},
	{"WANDevice.i.WANConnectionDevice.i.WANPPPConnection.i.",
			(void *)_WANDevice_i_WANConnectionDevice_i_WANPPPConnection_i, (char *)2},
	{"WANDevice.i.WANConnectionDevice.i.WANPPPConnection.i.PortMapping.i.",
			(void *)_WANDevice_i_WANConnectionDevice_i_WANPPPConnection_i_PortMapping_i, (char *)0},
	{"WANDevice.i.WANConnectionDevice.i.WANPPPConnection.i.Stats.",
			(void *)_WANDevice_i_WANConnectionDevice_i_WANPPPConnection_i_Stats, (char *)0},
	{NULL, NULL, 0}
};

int check_parameter(struct object_datamodel *a);

#endif	/* End of _CWMP_DATAMODEL_H_ */
