/* soapStub.h
   Generated by gSOAP 2.7.17 from cwmp-1-2.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_cwmp	"urn:dslforum-org:cwmp-1-2"
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (13)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

#ifndef SOAP_TYPE_cwmp__AccessListValueType
#define SOAP_TYPE_cwmp__AccessListValueType (28)
/* cwmp:AccessListValueType */
enum cwmp__AccessListValueType {cwmp__AccessListValueType__Subscriber = 0};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterAttributeNotificationValueType
#define SOAP_TYPE_cwmp__ParameterAttributeNotificationValueType (29)
/* cwmp:ParameterAttributeNotificationValueType */
enum cwmp__ParameterAttributeNotificationValueType {cwmp__ParameterAttributeNotificationValueType__0 = 0, cwmp__ParameterAttributeNotificationValueType__1 = 1, cwmp__ParameterAttributeNotificationValueType__2 = 2, cwmp__ParameterAttributeNotificationValueType__3 = 3, cwmp__ParameterAttributeNotificationValueType__4 = 4, cwmp__ParameterAttributeNotificationValueType__5 = 5, cwmp__ParameterAttributeNotificationValueType__6 = 6};
#endif

#ifndef SOAP_TYPE_cwmp__TransferStateType
#define SOAP_TYPE_cwmp__TransferStateType (30)
/* cwmp:TransferStateType */
enum cwmp__TransferStateType {cwmp__TransferStateType__1 = 1, cwmp__TransferStateType__2 = 2, cwmp__TransferStateType__3 = 3};
#endif

#ifndef SOAP_TYPE_cwmp__DeploymentUnitState
#define SOAP_TYPE_cwmp__DeploymentUnitState (32)
/* cwmp:DeploymentUnitState */
enum cwmp__DeploymentUnitState {cwmp__DeploymentUnitState__Installed = 0, cwmp__DeploymentUnitState__Uninstalled = 1, cwmp__DeploymentUnitState__Failed = 2};
#endif

#ifndef SOAP_TYPE_cwmp__DefaultDeploymentUnitOperationType
#define SOAP_TYPE_cwmp__DefaultDeploymentUnitOperationType (33)
/* cwmp:DefaultDeploymentUnitOperationType */
enum cwmp__DefaultDeploymentUnitOperationType {cwmp__DefaultDeploymentUnitOperationType__Install = 0, cwmp__DefaultDeploymentUnitOperationType__Update = 1, cwmp__DefaultDeploymentUnitOperationType__Uninstall = 2};
#endif

#ifndef SOAP_TYPE_cwmp__TransferCompleteCPEFaultCodeType
#define SOAP_TYPE_cwmp__TransferCompleteCPEFaultCodeType (34)
/* cwmp:TransferCompleteCPEFaultCodeType */
enum cwmp__TransferCompleteCPEFaultCodeType {cwmp__TransferCompleteCPEFaultCodeType__9001 = 9001, cwmp__TransferCompleteCPEFaultCodeType__9002 = 9002, cwmp__TransferCompleteCPEFaultCodeType__9010 = 9010, cwmp__TransferCompleteCPEFaultCodeType__9011 = 9011, cwmp__TransferCompleteCPEFaultCodeType__9012 = 9012, cwmp__TransferCompleteCPEFaultCodeType__9014 = 9014, cwmp__TransferCompleteCPEFaultCodeType__9015 = 9015, cwmp__TransferCompleteCPEFaultCodeType__9016 = 9016, cwmp__TransferCompleteCPEFaultCodeType__9017 = 9017, cwmp__TransferCompleteCPEFaultCodeType__9018 = 9018, cwmp__TransferCompleteCPEFaultCodeType__9019 = 9019, cwmp__TransferCompleteCPEFaultCodeType__9020 = 9020};
#endif

#ifndef SOAP_TYPE_cwmp__DeploymentUnitCPEFaultCodeType
#define SOAP_TYPE_cwmp__DeploymentUnitCPEFaultCodeType (35)
/* cwmp:DeploymentUnitCPEFaultCodeType */
enum cwmp__DeploymentUnitCPEFaultCodeType {cwmp__DeploymentUnitCPEFaultCodeType__9001 = 9001, cwmp__DeploymentUnitCPEFaultCodeType__9003 = 9003, cwmp__DeploymentUnitCPEFaultCodeType__9012 = 9012, cwmp__DeploymentUnitCPEFaultCodeType__9013 = 9013, cwmp__DeploymentUnitCPEFaultCodeType__9015 = 9015, cwmp__DeploymentUnitCPEFaultCodeType__9016 = 9016, cwmp__DeploymentUnitCPEFaultCodeType__9017 = 9017, cwmp__DeploymentUnitCPEFaultCodeType__9018 = 9018, cwmp__DeploymentUnitCPEFaultCodeType__9022 = 9022, cwmp__DeploymentUnitCPEFaultCodeType__9023 = 9023, cwmp__DeploymentUnitCPEFaultCodeType__9024 = 9024, cwmp__DeploymentUnitCPEFaultCodeType__9025 = 9025, cwmp__DeploymentUnitCPEFaultCodeType__9026 = 9026, cwmp__DeploymentUnitCPEFaultCodeType__9027 = 9027, cwmp__DeploymentUnitCPEFaultCodeType__9028 = 9028, cwmp__DeploymentUnitCPEFaultCodeType__9029 = 9029, cwmp__DeploymentUnitCPEFaultCodeType__9030 = 9030, cwmp__DeploymentUnitCPEFaultCodeType__9031 = 9031, cwmp__DeploymentUnitCPEFaultCodeType__9032 = 9032};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_State
#define SOAP_TYPE__cwmp__OptionStruct_State (54)
/* cwmp:OptionStruct-State */
enum _cwmp__OptionStruct_State {_cwmp__OptionStruct_State__0 = 0, _cwmp__OptionStruct_State__1 = 1, _cwmp__OptionStruct_State__2 = 2, _cwmp__OptionStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_Mode
#define SOAP_TYPE__cwmp__OptionStruct_Mode (55)
/* cwmp:OptionStruct-Mode */
enum _cwmp__OptionStruct_Mode {_cwmp__OptionStruct_Mode__0 = 0, _cwmp__OptionStruct_Mode__1 = 1, _cwmp__OptionStruct_Mode__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_IsTransferable
#define SOAP_TYPE__cwmp__OptionStruct_IsTransferable (57)
/* cwmp:OptionStruct-IsTransferable */
enum _cwmp__OptionStruct_IsTransferable {_cwmp__OptionStruct_IsTransferable__0 = 0, _cwmp__OptionStruct_IsTransferable__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse_Status
#define SOAP_TYPE__cwmp__SetParameterValuesResponse_Status (70)
/* cwmp:SetParameterValuesResponse-Status */
enum _cwmp__SetParameterValuesResponse_Status {_cwmp__SetParameterValuesResponse_Status__0 = 0, _cwmp__SetParameterValuesResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__AddObjectResponse_Status
#define SOAP_TYPE__cwmp__AddObjectResponse_Status (89)
/* cwmp:AddObjectResponse-Status */
enum _cwmp__AddObjectResponse_Status {_cwmp__AddObjectResponse_Status__0 = 0, _cwmp__AddObjectResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse_Status
#define SOAP_TYPE__cwmp__DeleteObjectResponse_Status (92)
/* cwmp:DeleteObjectResponse-Status */
enum _cwmp__DeleteObjectResponse_Status {_cwmp__DeleteObjectResponse_Status__0 = 0, _cwmp__DeleteObjectResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__DownloadResponse_Status
#define SOAP_TYPE__cwmp__DownloadResponse_Status (95)
/* cwmp:DownloadResponse-Status */
enum _cwmp__DownloadResponse_Status {_cwmp__DownloadResponse_Status__0 = 0, _cwmp__DownloadResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__UploadResponse_Status
#define SOAP_TYPE__cwmp__UploadResponse_Status (114)
/* cwmp:UploadResponse-Status */
enum _cwmp__UploadResponse_Status {_cwmp__UploadResponse_Status__0 = 0, _cwmp__UploadResponse_Status__1 = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_SOAP_ENC__base64
#define SOAP_TYPE_SOAP_ENC__base64 (7)
/* Base64 schema type: */
struct SOAP_ENC__base64
{
	unsigned char *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp__TransferCompleteFaultStruct
#define SOAP_TYPE_cwmp__TransferCompleteFaultStruct (36)
/* cwmp:TransferCompleteFaultStruct */
struct cwmp__TransferCompleteFaultStruct
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__DeploymentUnitFaultStruct
#define SOAP_TYPE_cwmp__DeploymentUnitFaultStruct (37)
/* cwmp:DeploymentUnitFaultStruct */
struct cwmp__DeploymentUnitFaultStruct
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterValueStruct
#define SOAP_TYPE_cwmp__ParameterValueStruct (38)
/* cwmp:ParameterValueStruct */
struct cwmp__ParameterValueStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:anySimpleType */
};
#endif

#ifndef SOAP_TYPE_cwmp__DeviceIdStruct
#define SOAP_TYPE_cwmp__DeviceIdStruct (39)
/* cwmp:DeviceIdStruct */
struct cwmp__DeviceIdStruct
{
	char *Manufacturer;	/* required element of type xsd:string */
	char *OUI;	/* required element of type xsd:string */
	char *ProductClass;	/* required element of type xsd:string */
	char *SerialNumber;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__EventStruct
#define SOAP_TYPE_cwmp__EventStruct (40)
/* cwmp:EventStruct */
struct cwmp__EventStruct
{
	char *EventCode;	/* required element of type cwmp:EventCodeType */
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterInfoStruct
#define SOAP_TYPE_cwmp__ParameterInfoStruct (41)
/* cwmp:ParameterInfoStruct */
struct cwmp__ParameterInfoStruct
{
	char *Name;	/* required element of type xsd:string */
	enum xsd__boolean Writable;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterAttributesStruct
#define SOAP_TYPE_cwmp__SetParameterAttributesStruct (42)
/* cwmp:SetParameterAttributesStruct */
struct cwmp__SetParameterAttributesStruct
{
	char *Name;	/* required element of type xsd:string */
	enum xsd__boolean NotificationChange;	/* required element of type xsd:boolean */
	enum cwmp__ParameterAttributeNotificationValueType Notification;	/* required element of type cwmp:ParameterAttributeNotificationValueType */
	enum xsd__boolean AccessListChange;	/* required element of type xsd:boolean */
	struct AccessList *AccessList;	/* required element of type ArrayOfAccessListValueType */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterAttributeStruct
#define SOAP_TYPE_cwmp__ParameterAttributeStruct (45)
/* cwmp:ParameterAttributeStruct */
struct cwmp__ParameterAttributeStruct
{
	char *Name;	/* required element of type xsd:string */
	enum cwmp__ParameterAttributeNotificationValueType Notification;	/* required element of type cwmp:ParameterAttributeNotificationValueType */
	struct AccessList *AccessList;	/* required element of type ArrayOfAccessListValueType */
};
#endif

#ifndef SOAP_TYPE_cwmp__TimeWindowStruct
#define SOAP_TYPE_cwmp__TimeWindowStruct (46)
/* cwmp:TimeWindowStruct */
struct cwmp__TimeWindowStruct
{
	unsigned int WindowStart;	/* required element of type xsd:unsignedInt */
	unsigned int WindowEnd;	/* required element of type xsd:unsignedInt */
	char *WindowMode;	/* required element of type cwmp:TimeWindowModeValueType */
	char *UserMessage;	/* required element of type xsd:string */
	int MaxRetries;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_cwmp__QueuedTransferStruct
#define SOAP_TYPE_cwmp__QueuedTransferStruct (47)
/* cwmp:QueuedTransferStruct */
struct cwmp__QueuedTransferStruct
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	enum cwmp__TransferStateType State;	/* required element of type cwmp:TransferStateType */
};
#endif

#ifndef SOAP_TYPE_cwmp__AllQueuedTransferStruct
#define SOAP_TYPE_cwmp__AllQueuedTransferStruct (48)
/* cwmp:AllQueuedTransferStruct */
struct cwmp__AllQueuedTransferStruct
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	enum cwmp__TransferStateType State;	/* required element of type cwmp:TransferStateType */
	enum xsd__boolean IsDownload;	/* required element of type xsd:boolean */
	char *FileType;	/* required element of type cwmp:TransferFileType */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__OperationStruct
#define SOAP_TYPE_cwmp__OperationStruct (49)
/* cwmp:OperationStruct */
struct cwmp__OperationStruct
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_cwmp__OpResultStruct
#define SOAP_TYPE_cwmp__OpResultStruct (50)
/* cwmp:OpResultStruct */
struct cwmp__OpResultStruct
{
	char *UUID;	/* required element of type cwmp:DeploymentUnitUUID */
	char *DeploymentUnitRef;	/* required element of type xsd:string */
	char *Version;	/* required element of type xsd:string */
	enum cwmp__DeploymentUnitState CurrentState;	/* required element of type cwmp:DeploymentUnitState */
	enum xsd__boolean Resolved;	/* required element of type xsd:boolean */
	char *ExecutionUnitRefList;	/* required element of type xsd:string */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
	struct cwmp__DeploymentUnitFaultStruct *Fault;	/* required element of type cwmp:DeploymentUnitFaultStruct */
};
#endif

#ifndef SOAP_TYPE_cwmp__OptionStruct
#define SOAP_TYPE_cwmp__OptionStruct (53)
/* cwmp:OptionStruct */
struct cwmp__OptionStruct
{
	char *OptionName;	/* required element of type xsd:string */
	unsigned int VoucherSN;	/* required element of type xsd:unsignedInt */
	enum _cwmp__OptionStruct_State State;	/* required element of type cwmp:OptionStruct-State */
	enum _cwmp__OptionStruct_Mode Mode;	/* required element of type cwmp:OptionStruct-Mode */
	time_t StartDate;	/* required element of type xsd:dateTime */
	time_t *ExpirationDate;	/* optional element of type xsd:dateTime */
	enum _cwmp__OptionStruct_IsTransferable IsTransferable;	/* required element of type cwmp:OptionStruct-IsTransferable */
};
#endif

#ifndef SOAP_TYPE_cwmp__ArgStruct
#define SOAP_TYPE_cwmp__ArgStruct (58)
/* cwmp:ArgStruct */
struct cwmp__ArgStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__Fault_SetParameterValuesFault
#define SOAP_TYPE__cwmp__Fault_SetParameterValuesFault (60)
/* cwmp:Fault-SetParameterValuesFault */
struct _cwmp__Fault_SetParameterValuesFault
{
	char *ParameterName;	/* required element of type xsd:string */
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__Fault
#define SOAP_TYPE__cwmp__Fault (59)
/* cwmp:Fault */
struct _cwmp__Fault
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* optional element of type xsd:string */
	int __sizeSetParameterValuesFault;	/* sequence of elements <SetParameterValuesFault> */
	struct _cwmp__Fault_SetParameterValuesFault *SetParameterValuesFault;	/* optional element of type cwmp:Fault-SetParameterValuesFault */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetRPCMethods
#define SOAP_TYPE__cwmp__GetRPCMethods (62)
/* cwmp:GetRPCMethods */
struct _cwmp__GetRPCMethods
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetRPCMethodsResponse
#define SOAP_TYPE__cwmp__GetRPCMethodsResponse (63)
/* cwmp:GetRPCMethodsResponse */
struct _cwmp__GetRPCMethodsResponse
{
	struct MethodList *MethodList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValues
#define SOAP_TYPE__cwmp__SetParameterValues (66)
/* cwmp:SetParameterValues */
struct _cwmp__SetParameterValues
{
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse
#define SOAP_TYPE__cwmp__SetParameterValuesResponse (69)
/* cwmp:SetParameterValuesResponse */
struct _cwmp__SetParameterValuesResponse
{
	enum _cwmp__SetParameterValuesResponse_Status Status;	/* required element of type cwmp:SetParameterValuesResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterValues
#define SOAP_TYPE__cwmp__GetParameterValues (71)
/* cwmp:GetParameterValues */
struct _cwmp__GetParameterValues
{
	struct ParameterNames *ParameterNames;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterValuesResponse
#define SOAP_TYPE__cwmp__GetParameterValuesResponse (74)
/* cwmp:GetParameterValuesResponse */
struct _cwmp__GetParameterValuesResponse
{
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterNames
#define SOAP_TYPE__cwmp__GetParameterNames (75)
/* cwmp:GetParameterNames */
struct _cwmp__GetParameterNames
{
	char *ParameterPath;	/* required element of type xsd:string */
	enum xsd__boolean NextLevel;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterNamesResponse
#define SOAP_TYPE__cwmp__GetParameterNamesResponse (76)
/* cwmp:GetParameterNamesResponse */
struct _cwmp__GetParameterNamesResponse
{
	struct ParameterInfoList *ParameterList;	/* required element of type ArrayOfParameterInfoStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributes
#define SOAP_TYPE__cwmp__SetParameterAttributes (79)
/* cwmp:SetParameterAttributes */
struct _cwmp__SetParameterAttributes
{
	struct SetParameterAttributesList *ParameterList;	/* required element of type ArrayOfSetParameterAttributesStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributesResponse
#define SOAP_TYPE__cwmp__SetParameterAttributesResponse (82)
/* cwmp:SetParameterAttributesResponse */
struct _cwmp__SetParameterAttributesResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterAttributes
#define SOAP_TYPE__cwmp__GetParameterAttributes (83)
/* cwmp:GetParameterAttributes */
struct _cwmp__GetParameterAttributes
{
	struct ParameterNames *ParameterNames;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterAttributesResponse
#define SOAP_TYPE__cwmp__GetParameterAttributesResponse (84)
/* cwmp:GetParameterAttributesResponse */
struct _cwmp__GetParameterAttributesResponse
{
	struct ParameterAttributeList *ParameterList;	/* required element of type ArrayOfParameterAttributeStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__AddObject
#define SOAP_TYPE__cwmp__AddObject (87)
/* cwmp:AddObject */
struct _cwmp__AddObject
{
	char *ObjectName;	/* required element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__AddObjectResponse
#define SOAP_TYPE__cwmp__AddObjectResponse (88)
/* cwmp:AddObjectResponse */
struct _cwmp__AddObjectResponse
{
	unsigned int InstanceNumber;	/* required element of type xsd:unsignedInt */
	enum _cwmp__AddObjectResponse_Status Status;	/* required element of type cwmp:AddObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObject
#define SOAP_TYPE__cwmp__DeleteObject (90)
/* cwmp:DeleteObject */
struct _cwmp__DeleteObject
{
	char *ObjectName;	/* required element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse
#define SOAP_TYPE__cwmp__DeleteObjectResponse (91)
/* cwmp:DeleteObjectResponse */
struct _cwmp__DeleteObjectResponse
{
	enum _cwmp__DeleteObjectResponse_Status Status;	/* required element of type cwmp:DeleteObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__Download
#define SOAP_TYPE__cwmp__Download (93)
/* cwmp:Download */
struct _cwmp__Download
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	char *FileType;	/* required element of type cwmp:DownloadFileType */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *SuccessURL;	/* required element of type xsd:string */
	char *FailureURL;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__DownloadResponse
#define SOAP_TYPE__cwmp__DownloadResponse (94)
/* cwmp:DownloadResponse */
struct _cwmp__DownloadResponse
{
	enum _cwmp__DownloadResponse_Status Status;	/* required element of type cwmp:DownloadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__Reboot
#define SOAP_TYPE__cwmp__Reboot (96)
/* cwmp:Reboot */
struct _cwmp__Reboot
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__RebootResponse
#define SOAP_TYPE__cwmp__RebootResponse (97)
/* cwmp:RebootResponse */
struct _cwmp__RebootResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetQueuedTransfers
#define SOAP_TYPE__cwmp__GetQueuedTransfers (98)
/* cwmp:GetQueuedTransfers */
struct _cwmp__GetQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetQueuedTransfersResponse
#define SOAP_TYPE__cwmp__GetQueuedTransfersResponse (99)
/* cwmp:GetQueuedTransfersResponse */
struct _cwmp__GetQueuedTransfersResponse
{
	struct TransferList *TransferList;	/* required element of type ArrayOfQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleInform
#define SOAP_TYPE__cwmp__ScheduleInform (102)
/* cwmp:ScheduleInform */
struct _cwmp__ScheduleInform
{
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleInformResponse
#define SOAP_TYPE__cwmp__ScheduleInformResponse (103)
/* cwmp:ScheduleInformResponse */
struct _cwmp__ScheduleInformResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__SetVouchers
#define SOAP_TYPE__cwmp__SetVouchers (104)
/* cwmp:SetVouchers */
struct _cwmp__SetVouchers
{
	struct VoucherList *VoucherList;	/* required element of type ArrayOfbase64 */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetVouchersResponse
#define SOAP_TYPE__cwmp__SetVouchersResponse (107)
/* cwmp:SetVouchersResponse */
struct _cwmp__SetVouchersResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetOptions
#define SOAP_TYPE__cwmp__GetOptions (108)
/* cwmp:GetOptions */
struct _cwmp__GetOptions
{
	char *OptionName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetOptionsResponse
#define SOAP_TYPE__cwmp__GetOptionsResponse (109)
/* cwmp:GetOptionsResponse */
struct _cwmp__GetOptionsResponse
{
	struct OptionList *OptionList;	/* required element of type ArrayOfOptionStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__Upload
#define SOAP_TYPE__cwmp__Upload (112)
/* cwmp:Upload */
struct _cwmp__Upload
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	char *FileType;	/* required element of type cwmp:UploadFileType */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp__UploadResponse
#define SOAP_TYPE__cwmp__UploadResponse (113)
/* cwmp:UploadResponse */
struct _cwmp__UploadResponse
{
	enum _cwmp__UploadResponse_Status Status;	/* required element of type cwmp:UploadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__FactoryReset
#define SOAP_TYPE__cwmp__FactoryReset (115)
/* cwmp:FactoryReset */
struct _cwmp__FactoryReset
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__FactoryResetResponse
#define SOAP_TYPE__cwmp__FactoryResetResponse (116)
/* cwmp:FactoryResetResponse */
struct _cwmp__FactoryResetResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetAllQueuedTransfers
#define SOAP_TYPE__cwmp__GetAllQueuedTransfers (117)
/* cwmp:GetAllQueuedTransfers */
struct _cwmp__GetAllQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetAllQueuedTransfersResponse
#define SOAP_TYPE__cwmp__GetAllQueuedTransfersResponse (118)
/* cwmp:GetAllQueuedTransfersResponse */
struct _cwmp__GetAllQueuedTransfersResponse
{
	struct AllTransferList *TransferList;	/* required element of type ArrayOfAllQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleDownload
#define SOAP_TYPE__cwmp__ScheduleDownload (121)
/* cwmp:ScheduleDownload */
struct _cwmp__ScheduleDownload
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	char *FileType;	/* required element of type cwmp:DownloadFileType */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	struct TimeWindowList *TimeWindowList;	/* required element of type ArrayOfTimeWindowStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleDownloadResponse
#define SOAP_TYPE__cwmp__ScheduleDownloadResponse (124)
/* cwmp:ScheduleDownloadResponse */
struct _cwmp__ScheduleDownloadResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__CancelTransfer
#define SOAP_TYPE__cwmp__CancelTransfer (125)
/* cwmp:CancelTransfer */
struct _cwmp__CancelTransfer
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__CancelTransferResponse
#define SOAP_TYPE__cwmp__CancelTransferResponse (126)
/* cwmp:CancelTransferResponse */
struct _cwmp__CancelTransferResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__ChangeDUState
#define SOAP_TYPE__cwmp__ChangeDUState (127)
/* cwmp:ChangeDUState */
struct _cwmp__ChangeDUState
{
	int __sizeOperations;	/* sequence of elements <Operations> */
	struct cwmp__OperationStruct *Operations;	/* required element of type cwmp:OperationStruct */
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__ChangeDUStateResponse
#define SOAP_TYPE__cwmp__ChangeDUStateResponse (129)
/* cwmp:ChangeDUStateResponse */
struct _cwmp__ChangeDUStateResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__Inform
#define SOAP_TYPE__cwmp__Inform (130)
/* cwmp:Inform */
struct _cwmp__Inform
{
	struct cwmp__DeviceIdStruct *DeviceId;	/* required element of type cwmp:DeviceIdStruct */
	struct EventList *Event;	/* required element of type ArrayOfEventStruct */
	unsigned int MaxEnvelopes;	/* required element of type xsd:unsignedInt */
	time_t CurrentTime;	/* required element of type xsd:dateTime */
	unsigned int RetryCount;	/* required element of type xsd:unsignedInt */
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__InformResponse
#define SOAP_TYPE__cwmp__InformResponse (134)
/* cwmp:InformResponse */
struct _cwmp__InformResponse
{
	unsigned int MaxEnvelopes;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp__TransferComplete
#define SOAP_TYPE__cwmp__TransferComplete (135)
/* cwmp:TransferComplete */
struct _cwmp__TransferComplete
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	struct cwmp__TransferCompleteFaultStruct *FaultStruct;	/* required element of type cwmp:TransferCompleteFaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__TransferCompleteResponse
#define SOAP_TYPE__cwmp__TransferCompleteResponse (137)
/* cwmp:TransferCompleteResponse */
struct _cwmp__TransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__AutonomousTransferComplete
#define SOAP_TYPE__cwmp__AutonomousTransferComplete (138)
/* cwmp:AutonomousTransferComplete */
struct _cwmp__AutonomousTransferComplete
{
	char *AnnounceURL;	/* required element of type xsd:string */
	char *TransferURL;	/* required element of type xsd:string */
	enum xsd__boolean IsDownload;	/* required element of type xsd:boolean */
	char *FileType;	/* required element of type cwmp:TransferFileType */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	struct cwmp__TransferCompleteFaultStruct *FaultStruct;	/* required element of type cwmp:TransferCompleteFaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__AutonomousTransferCompleteResponse
#define SOAP_TYPE__cwmp__AutonomousTransferCompleteResponse (139)
/* cwmp:AutonomousTransferCompleteResponse */
struct _cwmp__AutonomousTransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__Kicked
#define SOAP_TYPE__cwmp__Kicked (140)
/* cwmp:Kicked */
struct _cwmp__Kicked
{
	char *Command;	/* required element of type xsd:string */
	char *Referer;	/* required element of type xsd:string */
	char *Arg;	/* required element of type xsd:string */
	char *Next;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__KickedResponse
#define SOAP_TYPE__cwmp__KickedResponse (141)
/* cwmp:KickedResponse */
struct _cwmp__KickedResponse
{
	char *NextURL;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__RequestDownload
#define SOAP_TYPE__cwmp__RequestDownload (142)
/* cwmp:RequestDownload */
struct _cwmp__RequestDownload
{
	char *FileType;	/* required element of type cwmp:DownloadFileType */
	struct FileTypeArg *FileTypeArg;	/* required element of type ArrayOfArgStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__RequestDownloadResponse
#define SOAP_TYPE__cwmp__RequestDownloadResponse (145)
/* cwmp:RequestDownloadResponse */
struct _cwmp__RequestDownloadResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__DUStateChangeComplete
#define SOAP_TYPE__cwmp__DUStateChangeComplete (146)
/* cwmp:DUStateChangeComplete */
struct _cwmp__DUStateChangeComplete
{
	int __sizeResults;	/* sequence of elements <Results> */
	struct cwmp__OpResultStruct *Results;	/* required element of type cwmp:OpResultStruct */
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__DUStateChangeCompleteResponse
#define SOAP_TYPE__cwmp__DUStateChangeCompleteResponse (148)
/* cwmp:DUStateChangeCompleteResponse */
struct _cwmp__DUStateChangeCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__AutonomousDUStateChangeComplete
#define SOAP_TYPE__cwmp__AutonomousDUStateChangeComplete (149)
/* cwmp:AutonomousDUStateChangeComplete */
struct _cwmp__AutonomousDUStateChangeComplete
{
	int __sizeResults;	/* sequence of elements <Results> */
	struct cwmp__AutonOpResultStruct *Results;	/* required element of type cwmp:AutonOpResultStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__AutonomousDUStateChangeCompleteResponse
#define SOAP_TYPE__cwmp__AutonomousDUStateChangeCompleteResponse (152)
/* cwmp:AutonomousDUStateChangeCompleteResponse */
struct _cwmp__AutonomousDUStateChangeCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ParameterNames
#define SOAP_TYPE_ParameterNames (72)
/* SOAP encoded array of xsd:string schema type: */
struct ParameterNames
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterValueList
#define SOAP_TYPE_ParameterValueList (67)
/* SOAP encoded array of cwmp:ParameterValueStruct schema type: */
struct ParameterValueList
{
	struct cwmp__ParameterValueStruct **__ptrParameterValueStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_MethodList
#define SOAP_TYPE_MethodList (64)
/* SOAP encoded array of xsd:string schema type: */
struct MethodList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_EventList
#define SOAP_TYPE_EventList (132)
/* SOAP encoded array of cwmp:EventStruct schema type: */
struct EventList
{
	struct cwmp__EventStruct **__ptrEventStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterInfoList
#define SOAP_TYPE_ParameterInfoList (77)
/* SOAP encoded array of cwmp:ParameterInfoStruct schema type: */
struct ParameterInfoList
{
	struct cwmp__ParameterInfoStruct **__ptrParameterInfoStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AccessList
#define SOAP_TYPE_AccessList (43)
/* SOAP encoded array of cwmp:AccessListValueType schema type: */
struct AccessList
{
	enum cwmp__AccessListValueType *__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_SetParameterAttributesList
#define SOAP_TYPE_SetParameterAttributesList (80)
/* SOAP encoded array of cwmp:SetParameterAttributesStruct schema type: */
struct SetParameterAttributesList
{
	struct cwmp__SetParameterAttributesStruct **__ptrSetParameterAttributesStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterAttributeList
#define SOAP_TYPE_ParameterAttributeList (85)
/* SOAP encoded array of cwmp:ParameterAttributeStruct schema type: */
struct ParameterAttributeList
{
	struct cwmp__ParameterAttributeStruct **__ptrParameterAttributeStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_TimeWindowList
#define SOAP_TYPE_TimeWindowList (122)
/* SOAP encoded array of cwmp:TimeWindowStruct schema type: */
struct TimeWindowList
{
	struct cwmp__TimeWindowStruct **__ptrTimeWindowStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_TransferList
#define SOAP_TYPE_TransferList (100)
/* SOAP encoded array of cwmp:QueuedTransferStruct schema type: */
struct TransferList
{
	struct cwmp__QueuedTransferStruct **__ptrQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AllTransferList
#define SOAP_TYPE_AllTransferList (119)
/* SOAP encoded array of cwmp:AllQueuedTransferStruct schema type: */
struct AllTransferList
{
	struct cwmp__AllQueuedTransferStruct **__ptrAllQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp__InstallOpStruct
#define SOAP_TYPE_cwmp__InstallOpStruct (171)
/* cwmp:InstallOpStruct */
struct cwmp__InstallOpStruct
{
	char *URL;	/* required element of type xsd:anyURI */
	char *UUID;	/* optional element of type cwmp:DeploymentUnitUUID */
	char **Username;	/* optional element of type xsd:string */
	char **Password;	/* optional element of type xsd:string */
	char **ExecutionEnvRef;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__UpdateOpStruct
#define SOAP_TYPE_cwmp__UpdateOpStruct (172)
/* cwmp:UpdateOpStruct */
struct cwmp__UpdateOpStruct
{
	char *UUID;	/* optional element of type cwmp:DeploymentUnitUUID */
	char **Version;	/* optional element of type xsd:string */
	char **URL;	/* optional element of type xsd:anyURI */
	char **Username;	/* optional element of type xsd:string */
	char **Password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__UninstallOpStruct
#define SOAP_TYPE_cwmp__UninstallOpStruct (174)
/* cwmp:UninstallOpStruct */
struct cwmp__UninstallOpStruct
{
	char *UUID;	/* required element of type cwmp:DeploymentUnitUUID */
	char **Version;	/* optional element of type xsd:string */
	char **ExecutionEnvRef;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__AutonOpResultStruct
#define SOAP_TYPE_cwmp__AutonOpResultStruct (150)
/* cwmp:AutonOpResultStruct */
struct cwmp__AutonOpResultStruct
{
	char *UUID;	/* required element of type cwmp:DeploymentUnitUUID */
	char *DeploymentUnitRef;	/* required element of type xsd:string */
	char *Version;	/* required element of type xsd:string */
	enum cwmp__DeploymentUnitState CurrentState;	/* required element of type cwmp:DeploymentUnitState */
	enum xsd__boolean Resolved;	/* required element of type xsd:boolean */
	char *ExecutionUnitRefList;	/* required element of type xsd:string */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
	struct cwmp__DeploymentUnitFaultStruct *Fault;	/* required element of type cwmp:DeploymentUnitFaultStruct */
	char *OperationPerformed;	/* required element of type cwmp:DeploymentUnitOperationType */
};
#endif

#ifndef SOAP_TYPE_VoucherList
#define SOAP_TYPE_VoucherList (105)
/* SOAP encoded array of SOAP-ENC:base64 schema type: */
struct VoucherList
{
	struct SOAP_ENC__base64 **__ptrbase64;
	int __size;
};
#endif

#ifndef SOAP_TYPE_OptionList
#define SOAP_TYPE_OptionList (110)
/* SOAP encoded array of cwmp:OptionStruct schema type: */
struct OptionList
{
	struct cwmp__OptionStruct **__ptrOptionStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_FileTypeArg
#define SOAP_TYPE_FileTypeArg (143)
/* SOAP encoded array of cwmp:ArgStruct schema type: */
struct FileTypeArg
{
	struct cwmp__ArgStruct **__ptrArgStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE__cwmp__ID
#define SOAP_TYPE__cwmp__ID (181)
/* cwmp:ID */
struct _cwmp__ID
{
	char *__item;
	char *SOAP_ENV__mustUnderstand;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__HoldRequests
#define SOAP_TYPE__cwmp__HoldRequests (182)
/* cwmp:HoldRequests */
struct _cwmp__HoldRequests
{
	enum xsd__boolean __item;
	char *SOAP_ENV__mustUnderstand;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (183)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (184)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (186)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (189)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (190)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (11)
typedef char *xsd__anySimpleType;
#endif

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (12)
typedef char *xsd__anyURI;
#endif

#ifndef SOAP_TYPE_cwmp__DeploymentUnitOperationType
#define SOAP_TYPE_cwmp__DeploymentUnitOperationType (14)
typedef char *cwmp__DeploymentUnitOperationType;
#endif

#ifndef SOAP_TYPE_cwmp__CPEFaultCodeType
#define SOAP_TYPE_cwmp__CPEFaultCodeType (15)
typedef unsigned int cwmp__CPEFaultCodeType;
#endif

#ifndef SOAP_TYPE_cwmp__CPEExtensionFaultCodeType
#define SOAP_TYPE_cwmp__CPEExtensionFaultCodeType (16)
typedef unsigned int cwmp__CPEExtensionFaultCodeType;
#endif

#ifndef SOAP_TYPE_cwmp__CPEVendorFaultCodeType
#define SOAP_TYPE_cwmp__CPEVendorFaultCodeType (17)
typedef unsigned int cwmp__CPEVendorFaultCodeType;
#endif

#ifndef SOAP_TYPE_cwmp__ACSFaultCodeType
#define SOAP_TYPE_cwmp__ACSFaultCodeType (18)
typedef unsigned int cwmp__ACSFaultCodeType;
#endif

#ifndef SOAP_TYPE_cwmp__ACSVendorFaultCodeType
#define SOAP_TYPE_cwmp__ACSVendorFaultCodeType (19)
typedef unsigned int cwmp__ACSVendorFaultCodeType;
#endif

#ifndef SOAP_TYPE_cwmp__TransferFileType
#define SOAP_TYPE_cwmp__TransferFileType (20)
typedef char *cwmp__TransferFileType;
#endif

#ifndef SOAP_TYPE_cwmp__DownloadFileType
#define SOAP_TYPE_cwmp__DownloadFileType (21)
typedef char *cwmp__DownloadFileType;
#endif

#ifndef SOAP_TYPE_cwmp__UploadFileType
#define SOAP_TYPE_cwmp__UploadFileType (22)
typedef char *cwmp__UploadFileType;
#endif

#ifndef SOAP_TYPE_cwmp__EventCodeType
#define SOAP_TYPE_cwmp__EventCodeType (23)
typedef char *cwmp__EventCodeType;
#endif

#ifndef SOAP_TYPE_cwmp__TimeWindowModeValueType
#define SOAP_TYPE_cwmp__TimeWindowModeValueType (24)
typedef char *cwmp__TimeWindowModeValueType;
#endif

#ifndef SOAP_TYPE_cwmp__CommandKeyType
#define SOAP_TYPE_cwmp__CommandKeyType (25)
typedef char *cwmp__CommandKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__ObjectNameType
#define SOAP_TYPE_cwmp__ObjectNameType (26)
typedef char *cwmp__ObjectNameType;
#endif

#ifndef SOAP_TYPE_cwmp__ParameterKeyType
#define SOAP_TYPE_cwmp__ParameterKeyType (27)
typedef char *cwmp__ParameterKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__DeploymentUnitUUID
#define SOAP_TYPE_cwmp__DeploymentUnitUUID (31)
typedef char *cwmp__DeploymentUnitUUID;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
